version: '3.8'
services:
  mongo:
    image: mongo:6 
    container_name: mongo-stock 
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build: .
    container_name: stock-api 
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stockdb 
    depends_on:
      - mongo
  
volumes: 
  mongo-data:

networks:
  stock-network:
    driver: bridge